### ISSUE TITLE
Initial Provider Review

### ISSUE THREAD

**Issue by bill-rich** [huaweicloud/terraform-provider-flexibleengine#22]
Hello! 

My name is Bill, I'm a member of the Terraform team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking remaining items and discussion. The review was done on the git commit ab16332.

- [x] There are many sections of code that have been commented out. If they are not needed, it would probably be best to remove them to keep things clean. Here are a few examples.
  * `force_delete` commented out at https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_compute_instance_v2.go#L799-L805
  * Setting of `security_group` is at https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_compute_instance_v2.go#L547-L553
  * `certificates` is commented out at https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_elb_listener.go#L131-L135
  * Setting tags is commented at https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_s3_bucket.go#L774-L786
- [x] In some places the cloud is referred to as FlexibleEngine and in others it is OrangeCloud. Are these the same? If so, can the instances of OrangeCloud be changed to FlexibleEngine?
- [ ] Why are AWS resources included (list s3_bucket)? Could AWS provider be used instead of duplicating this work?
- [x] What is build_param_util.go used for? It doesn’t seem to be used anywhere. If it isn’t needed, can we remove it?
- [x] Can .zuul.yaml be deleted? We usually try to keep it to just travis.yml for CI.
- [ ] CHANGELOG.md needs to be filled in.

The provider is looking great. It looks like its mostly just a matter of getting a few items cleaned up.

Thanks,
Bill

**Comment by niuzhenguo** [comment]
Thanks @bill-rich for the review!
In fact, we have a [stable branch](https://github.com/huaweicloud/terraform-provider-flexibleengine/tree/stable/terraform) for your review in case of our new changes break it. I will go through the checklist above, and address them soon!

**Comment by niuzhenguo** [comment]
@bill-rich I finished 4 of 6 tasks above, please check out the stable/terraform branch!
And for the rest, please see my comments below:

- [ ] Why are AWS resources included (list s3_bucket)? Could AWS provider be used instead of duplicating this work?

The AWS s3 resources here is because we have an object storage service which is compatible with S3 but not completely same. Please let me know if this is allowed or we should change a resource name.

- [ ] CHANGELOG.md needs to be filled in.

As there are so many resources added since the project setup, we plan to add CHANGELOG after we make the first release in /terraform-providers, not sure if that makes sence.

Thanks,
Zhenguo

**Comment by niuzhenguo** [comment]
@bill-rich hi, could you please help to review this again, thanks!

**Comment by bill-rich** [comment]
@niuzhenguo Looks good! Thank you for getting those items addressed! 

The AWS resources seem fine. That makes sense to have resources to cover the object storage service. I'd say that as long as the resource names match the names as they're used on the cloud, it would be good to keep them as is.

For the CHANGELOG, I think it makes sense to not worry about backfilling it with all the previous changes, but I'd like to get a snapshot of where things are at before the provider gets pulled into terraform-providers. That way we've got a reference for the initial version. Something like [this](https://github.com/terraform-providers/terraform-provider-oraclepaas/blob/master/CHANGELOG.md) would be good.

**Comment by niuzhenguo** [comment]
@bill-rich Thanks, will fill the CHANGELOG soon!

**Comment by niuzhenguo** [comment]
@bill-rich I have updated the CHANGELOG for initial release of flexibleengine provider, please  check it out on stable/terraform branch, thanks!

**Comment by bill-rich** [comment]
@niuzhenguo Perfect! That looks great. I think the provider is ready to go!

**Comment by cgriggs01** [comment]
@niuzhenguo Thanks for addressing all of the feedback, we'll move forward with the provider release now!

This issue can be closed and I will follow up with you via email.

**Comment by niuzhenguo** [comment]
Thanks @bill-rich and @cgriggs01 , closing this!
