### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [huaweicloud/terraform-provider-flexibleengine#5]
Hello Team,

I’ve taken a look at the provider and would like to say it looks good so far. I do have feedback outlined below that I’d like to see addressed before we move on to the next steps.

#### Documentation: 
- The provider contains two variables in the schema, '[access_key](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/provider.go#L16)' and '[secret_key](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/provider.go#L23)' that are not documented on the [FlexibleEngine Provider](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/index.html.markdown) page.

- The ’[tenant_id](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_fw_policy_v2.go#L52)’ variable is not documented in the [fw_policy_v2](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/fw_policy_v2.html.markdown) docs.

- Variable name error: The [as_configuration_v1](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/as_configuration_v1.html.markdown#argument-reference) page states that the `personality` block supported variables are `file` and `contents` where as the [Resource Configuration](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_as_configuration_v1.go#L98) of this resource defines the two variable names as `path` and `content`. 

- The variable `connection_limit`  is documented in [lb_listener_v2](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/lb_listener_v2.html.markdown) but the declaration of the variable in the resource schema is commented out in [resource_flexibleengine_lb_listener_v2.go](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_lb_listener_v2.go#L86)

- There are a number resources in your website documentation that do not have corresponding resource files in the providers source code. These should be removed, or corresponding resources should be added. 
[blockstorage_volume_attach_v2](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/blockstorage_volume_attach_v2.html.markdown)
[blockstorage_volume_v1](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/blockstorage_volume_v1.html.markdown)
[compute_flavor_v2](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/compute_flavor_v2.html.markdown)
[identity_project_v3](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/identity_project_v3.html.markdown)
[identity_user_v3](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/identity_user_v3.html.markdown)
[lb_member_v1](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/lb_member_v1.html.markdown)
[lb_monitor_v1](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/lb_monitor_v1.html.markdown)
[lb_pool_v1](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/lb_pool_v1.html.markdown)
[lb_vip_v1](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/website/docs/r/lb_vip_v1.html.markdown)

- Resources and Data Source that are in the providers code base but are missing proper documentation. Please add documentation files for each of these. 
[resource_flexibleengine_elb_backend](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_elb_backend.go)
[resource_flexibleengine_elb_health](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_elb_health.go)
[resource_flexibleengine_elb_listener](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_elb_listener.go)
[resource_flexibleengine_elb_loadbalancer](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_elb_loadbalancer.go)
[data_source_flexibleengine_s3_bucket_object](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/data_source_flexibleengine_s3_bucket_object.go)

#### Acceptance Testing: 

- A few of the resource files are missing their respective acceptance test files, could you please add tests for the following resources:
[resource_flexibleengine_as_group_v1.go](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_as_group_v1.go)
[resource_flexibleengine_as_policy_v1.go](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_as_policy_v1.go)
[resource_flexibleengine_networking_router_route_v2.go](https://github.com/huaweicloud/terraform-provider-flexibleengine/blob/master/flexibleengine/resource_flexibleengine_networking_router_route_v2.go)

- A number of your acceptance test files have tests that are commented out, thus not being run. It is understandable that some test will not pass since we are testing outside of your VPC, but it is important that your provider has the highest test coverage as possible. 

- The acceptance test ran successfully with the environment variable you provided, most of the test passed, only 10 of them failed. The failed tests output is as follows:
```
=== RUN   TestAccComputeV2FloatingIPAssociate_importBasic
--- FAIL: TestAccComputeV2FloatingIPAssociate_importBasic (141.00s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: Error allocating floating IP: Expected HTTP response code [201 202] when accessing [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/floatingips], but got 409 instead
		{"NeutronError":{"message":"Quota exceeded for resources: ['floatingip']","type":"OverQuota","detail":""}}
=== RUN   TestAccComputeV2FloatingIP_importBasic
--- FAIL: TestAccComputeV2FloatingIP_importBasic (8.41s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_compute_floatingip_v2.fip_1: 1 error(s) occurred:

		* flexibleengine_compute_floatingip_v2.fip_1: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST https://ecs.eu-west-0.prod-cloud-ocb.orange-business.com/v2/c3b53f0bb4e5492587159e07b54336ac/os-floating-ips], but got 403 instead
		{"forbidden":{"message":"allocated floatingIp quota exceeded.","code":"403"}}
=== RUN   TestAccNetworkingV2FloatingIP_importBasic
--- FAIL: TestAccNetworkingV2FloatingIP_importBasic (9.68s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: Error allocating floating IP: Expected HTTP response code [201 202] when accessing [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/floatingips], but got 409 instead
		{"NeutronError":{"message":"Quota exceeded for resources: ['floatingip']","type":"OverQuota","detail":""}}
=== RUN   TestAccComputeV2FloatingIPAssociate_basic
--- FAIL: TestAccComputeV2FloatingIPAssociate_basic (144.02s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: Error allocating floating IP: Expected HTTP response code [201 202] when accessing [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/floatingips], but got 409 instead
		{"NeutronError":{"message":"Quota exceeded for resources: ['floatingip']","type":"OverQuota","detail":""}}
=== RUN   TestAccComputeV2FloatingIPAssociate_fixedIP
--- FAIL: TestAccComputeV2FloatingIPAssociate_fixedIP (160.94s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: Error allocating floating IP: Expected HTTP response code [201 202] when accessing [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/floatingips], but got 409 instead
		{"NeutronError":{"message":"Quota exceeded for resources: ['floatingip']","type":"OverQuota","detail":""}}
=== RUN   TestAccComputeV2FloatingIPAssociate_attachToFirstNetwork
--- FAIL: TestAccComputeV2FloatingIPAssociate_attachToFirstNetwork (162.60s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: Error allocating floating IP: Expected HTTP response code [201 202] when accessing [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/floatingips], but got 409 instead
		{"NeutronError":{"message":"Quota exceeded for resources: ['floatingip']","type":"OverQuota","detail":""}}
=== RUN   TestAccComputeV2FloatingIPAssociate_attachNew
--- FAIL: TestAccComputeV2FloatingIPAssociate_attachNew (155.99s)
	testing.go:434: Step 0 error: Error applying: 2 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_2: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_2: Error allocating floating IP: Expected HTTP response code [201 202] when accessing [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/floatingips], but got 409 instead
		{"NeutronError":{"message":"Quota exceeded for resources: ['floatingip']","type":"OverQuota","detail":""}}
		* flexibleengine_networking_floatingip_v2.fip_1: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: Error allocating floating IP: Expected HTTP response code [201 202] when accessing [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/floatingips], but got 409 instead
		{"NeutronError":{"message":"Quota exceeded for resources: ['floatingip']","type":"OverQuota","detail":""}}
=== RUN   TestAccComputeV2FloatingIP_basic
--- FAIL: TestAccComputeV2FloatingIP_basic (8.07s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_compute_floatingip_v2.fip_1: 1 error(s) occurred:

		* flexibleengine_compute_floatingip_v2.fip_1: Error creating Floating IP: Expected HTTP response code [200] when accessing [POST https://ecs.eu-west-0.prod-cloud-ocb.orange-business.com/v2/c3b53f0bb4e5492587159e07b54336ac/os-floating-ips], but got 403 instead
		{"forbidden":{"message":"allocated floatingIp quota exceeded.","code":"403"}}
=== RUN   TestAccELBBackend_basic
JobStatus: &{Status:FAIL Entities:map[error:map[code:ELB.4001 message:{"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001]] JobID:ff80808262012937016202d3c8ea103b JobType:createELB ErrorCode:ELB.4001 FailReason:CreateIPTask-fail: {"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001}.
--- FAIL: TestAccELBBackend_basic (173.81s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_elb_loadbalancer.lb_orange_acctest: 1 error(s) occurred:

		* flexibleengine_elb_loadbalancer.lb_orange_acctest: Job failed with code ELB.4001: CreateIPTask-fail: {"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001.

=== RUN   TestAccELBHealth_basic
JobStatus: &{Status:FAIL Entities:map[error:map[code:ELB.4001 message:{"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001]] JobID:ff80808262012833016202d66db612b5 JobType:createELB ErrorCode:ELB.4001 FailReason:CreateIPTask-fail: {"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001}.
--- FAIL: TestAccELBHealth_basic (8.73s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_elb_loadbalancer.loadbalancer_1: 1 error(s) occurred:

		* flexibleengine_elb_loadbalancer.loadbalancer_1: Job failed with code ELB.4001: CreateIPTask-fail: {"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001.

=== RUN   TestAccELBListener_basic
JobStatus: &{Status:FAIL Entities:map[error:map[code:ELB.4001 message:{"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001]] JobID:ff80808262012937016202d68f47105b JobType:createELB ErrorCode:ELB.4001 FailReason:CreateIPTask-fail: {"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001}.
--- FAIL: TestAccELBListener_basic (8.58s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_elb_loadbalancer.loadbalancer_1: 1 error(s) occurred:

		* flexibleengine_elb_loadbalancer.loadbalancer_1: Job failed with code ELB.4001: CreateIPTask-fail: {"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001.

=== RUN   TestAccELBLoadBalancer_basic
JobStatus: &{Status:FAIL Entities:map[error:map[code:ELB.4001 message:{"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001]] JobID:ff80808262012a35016202d6afb31210 JobType:createELB ErrorCode:ELB.4001 FailReason:CreateIPTask-fail: {"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001}.
--- FAIL: TestAccELBLoadBalancer_basic (8.30s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_elb_loadbalancer.loadbalancer_1: 1 error(s) occurred:

		* flexibleengine_elb_loadbalancer.loadbalancer_1: Job failed with code ELB.4001: CreateIPTask-fail: {"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001.

=== RUN   TestAccELBLoadBalancer_secGroup
JobStatus: &{Status:FAIL Entities:map[error:map[code:ELB.4001 message:{"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001]] JobID:ff80808262012937016202d719b91073 JobType:createELB ErrorCode:ELB.4001 FailReason:CreateIPTask-fail: {"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001}.
--- FAIL: TestAccELBLoadBalancer_secGroup (62.57s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_elb_loadbalancer.loadbalancer_1: 1 error(s) occurred:

		* flexibleengine_elb_loadbalancer.loadbalancer_1: Job failed with code ELB.4001: CreateIPTask-fail: {"code":"VPC.0521","message":"{\"NeutronError\":{\"message\":\"Quota exceeded for resources: ['floatingip']\",\"type\":\"OverQuota\",\"detail\":\"\"}}"},errorcCode=ELB.4001.

=== RUN   TestAccNetworkingV2FloatingIP_basic
--- FAIL: TestAccNetworkingV2FloatingIP_basic (9.14s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: Error allocating floating IP: Expected HTTP response code [201 202] when accessing [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/floatingips], but got 409 instead
		{"NeutronError":{"message":"Quota exceeded for resources: ['floatingip']","type":"OverQuota","detail":""}}
=== RUN   TestAccNetworkingV2FloatingIP_timeout
--- FAIL: TestAccNetworkingV2FloatingIP_timeout (8.26s)
	testing.go:434: Step 0 error: Error applying: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: 1 error(s) occurred:

		* flexibleengine_networking_floatingip_v2.fip_1: Error allocating floating IP: Expected HTTP response code [201 202] when accessing [POST https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/floatingips], but got 409 instead
		{"NeutronError":{"message":"Quota exceeded for resources: ['floatingip']","type":"OverQuota","detail":""}}
```

----

Sorry for such a long issue, please let me know if you have any questions.

Best,
Chris

**Comment by freesky-edward** [comment]
@cgriggs01 thanks,  all of failed cases caused by account itself than code or tests. I will clear the residuum that produced before.

**Comment by niuzhenguo** [comment]
@cgriggs01 All issues have been addressed already, please help to review again when you got time. And I will create a stable branch named stable/terraform for your testing in case our new changes break it.

Also I will update the engagement webform GitHub repo with https://github.com/huaweicloud/terraform-provider-flexibleengine/tree/stable/terraform


Please let me know if anything we can help, I will keep this issue open to track your following up feedback.  Thanks in advance!

Best,
Zhenguo

**Comment by cgriggs01** [comment]
Thanks for making those changes. 

I am just wondering, how long does it take ya'll to run the acceptance tests in total?

Best,
Chris

**Comment by niuzhenguo** [comment]
@cgriggs01 My latest tests took 13209.205s in total. Is that too long for your nightly testing?

**Comment by cgriggs01** [comment]
No, thats not too long, I believe some of the largest providers take ~5 hours to run the acceptance tests. 

I was just wondering. Thanks

**Comment by niuzhenguo** [comment]
@cgriggs01 That's because the resource name collision, will clean up the resource to make the tests happy, sorry for the inconvenience.

**Comment by niuzhenguo** [comment]
@cgriggs01 I updated the infrastructure test account credentials in case new resources from someone else break your tests like above. Please take the new credentials from the webform, thanks!

**Comment by cgriggs01** [comment]
@niuzhenguo 

With the updated provider code and the new test credentials, I am still getting a number of the same failed tests:
[testacc.txt](https://github.com/huaweicloud/terraform-provider-flexibleengine/files/1835454/testacc.txt)

Please let me know if you have any thought on what is causing this issue?

**Comment by niuzhenguo** [comment]
@cgriggs01 I see many OverQuota issue with the pasted result file, will try to clean up resources and make more quota for the account. Will ping you when it's ready, sorry for that.

**Comment by niuzhenguo** [comment]
@cgriggs01 just confirmed with my team, that's because someone else used another account for testing which is in the same tenant with yours, so they break you again.

**Comment by niuzhenguo** [comment]
@cgriggs01 I have made some changes of the resources name for testing and cleaned up all unused resources on the test account. Please test again with the new provider code.

So sorry for the inconvenience, and I'm sure nobody will interrupt your tests again.
